services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
      - ENVIRONMENT=local
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123123
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - .:/usr/src/app/tmp # don't mount tmp directory
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL_SIDEKIQ: redis://redis:6379/0
volumes:
  pg_data:
  redis:
  bundle:
